#!/bin/bash 

function deal_util
{
	local name=$1
	local op=$2
	case $op in
		"clean")
			echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>> ${name} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
			if [ -e ${name} ]; then
				cd ${name}; make clean; cd -
			else
				echo "${name} is not exist!"
			fi
			;;
		*)
			echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>> ${name} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
			if [ -e ${name} ]; then
				cd ${name}; make clean && make && make install; cd -
			else
				echo "${name} is not exist!"
			fi
			;;
	esac
}


function print_usage
{
	local argc=$1
	echo -e "Usage: $1 [--help] [--with-openssl=DIR] [--with-zlib=DIR]"
	echo -e "--help 					print this message\n"
	echo -e "--clean					make clean"
	echo -e "--list					check all so"
	echo -e "--with-add=DIR				add one so"
	echo -e ""
}




LIBPATH=/usr/local/youhebuke
INCPATH=/usr/local/include/


### start ####
if [ $# != 0 ] ; then 
	if [ $1 == "--help" ]; then
		print_usage $0
		exit 0
	fi

	for arg in $*; do
		count=`echo $arg | grep "\-\-list" -c`
		if [ $count -eq 1 ]; then
			cat $0 | grep "deal_util" | grep -v "function" | grep -v "echo"
			exit
		fi

		count=`echo $arg | grep "\-\-with-add\=" -c`
		if [ $count -eq 1 ]; then
			add_path=`echo $arg | awk -F= '{print $2}'`
			echo "deal_util $add_path 	\$OP" >> $0
			exit
		fi

		case $arg in 
			"--clean") OP="clean" ;;
			"--start") OP="NULL"	;;
			*)       
				print_usage  $0
				exit
				;;
		esac
	done
fi 


test -e $LIBPATH  || mkdir $LIBPATH
test -e $INCPATH  || mkdir $INCPATH


count=`grep $LIBPATH /etc/ld.so.conf -c`
if [ $count -eq 0 ]; then
	echo "$LIBPATH" >> /etc/ld.so.conf
fi

deal_util threadpool_lu		$OP
deal_util threadpool_nginx	$OP
deal_util threadpool_self	$OP
deal_util FixedPool  		$OP
deal_util PLog 				$OP
deal_util mempool_nginx 	$OP
