CC = g++

all: merge_sort.cpp  quick_sort.cpp  raddix_sort.cpp
	$(CC) quick_sort.cpp -o quick_sort
	$(CC) merge_sort.cpp -o merge_sort
	$(CC) raddix_sort.cpp -o raddix_sort

clean:
	rm -rf quick_sort merge_sort raddix_sort
